### ISSUE TITLE
Update for 1.3.1

### ISSUE THREAD

**Issue by Otoris** [Crimsonfoxy/Statistician-v2#2] opened 2012-08-10 21:38 UTC
Would it be possible for you to update this plugin to work with 1.3.1 Craftbukkit? The current version has some missing information on the new blocks and likes to completely crash servers for some reason. I'd really appreciate it if you could update! 

Thanks so much!

**Comment by Coryf88** [comment] 2012-08-14 02:57
I'm currently working on getting my dev environment setup again (had a hard drive failure). So, I will be working on updating it to 1.3.1 and pushing the update either late 14th or early 15th. Do you have any more information about the crashing, any errors/exceptions or ability to reproduce it?

**Comment by Otoris** [comment] 2012-08-14 03:03
Here's the error:

2012-08-08 00:21:02 [SEVERE] Exception in thread "Timer-0" 
2012-08-08 00:21:02 [SEVERE] java.lang.NullPointerException
2012-08-08 00:21:02 [SEVERE]    at com.ChaseHQ.Statistician.Database.DBSynchDataGetSet.incrementValue(DBSynchDataGetSet.java:74)
2012-08-08 00:21:02 [SEVERE]    at com.ChaseHQ.Statistician.Stats.PlayerData._processData(PlayerData.java:152)
2012-08-08 00:21:02 [SEVERE]    at com.ChaseHQ.Statistician.DataProcessor.run(DataProcessor.java:22)
2012-08-08 00:21:02 [SEVERE]    at java.util.TimerThread.mainLoop(Timer.java:512)
2012-08-08 00:21:02 [SEVERE]    at java.util.TimerThread.run(Timer.java:462)

It was random the three times it occurred, so I have no clue. :( Hope this helps a little though! Thanks for replying ^^

**Comment by Coryf88** [comment] 2012-08-14 03:16
That exception shouldn't cause the server to crash. I've seen people, I believe myself also, have had that in MC1.2.5 with no reports of crashing. If anything, some stats would be lost.

I will look into the cause of that exception and try to fix for the 1.3.1 update, otherwise simply ignore it for now, unless it is the source of the crashing.

**Comment by Coryf88** [comment] 2012-08-16 01:04
Fixed in [v2.0.11](http://dev.bukkit.org/server-mods/statisticianv2/files/22/). (Currently waiting for approval)

**Closed as completed by Coryf88** 2012-08-16 01:04 UTC
